import Head from 'next/head'
import { Container,Row,Col } from "react-bootstrap"
import Card from '../../Components/Card'
import sanity from "../../lib/sanity";
import BlockContent from "@sanity/block-content-to-react";
const workQuery = `*[_type=="work"]{...,
    team[]->}`;

    const Work = ({ works }) => { 
  return (
    <div>
      <Head>
        <title>Holo -Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    <main>
        <br />
        <br />
     <div className="customContainer" style={{minHeight:'600px'}}>
       <Row>
{works.map((e)=>{
  return (<Card image={e.card} title={e.title} description={e.description} key={e.title} id={e._id}/>)
})}
       </Row>
     </div>
    </main>
    </div>
  )
}
export const getStaticProps = async () => {
  const works = await sanity.fetch(workQuery);

  return {
    props: { works } // will be passed to the page component as props
  };
};

export default Work