import Head from 'next/head'
import { Container,Row,Col } from "react-bootstrap"
import Image from 'next/image'
import dummy from '../public/images/dummy.png'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Holo -Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    <main>
     <div className="customContainer" style={{height:'80vh'}}>
       <Row>
         <Col xl={7} style={{height:'50vh',marginTop:'30vh'}}>
           <p className="title1">We empower<br/> solving problems</p>
           <p className="body"> We exist to design a better world together. We try to understand the problems around us while we solve them one at a time.</p>
            <p className='overline'>Scroll to see Featured work</p>
         </Col>
         <Col xs={5}style={{height:'40vh',marginTop:'30vh'}}></Col>
       </Row>
     </div>
     <div className="customContainer" style={{minHeight:'600px'}}>
       <Row>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
       </Row>
     </div>
    </main>
    </div>
  )
}
