import Head from 'next/head'
import { Container,Row,Col } from "react-bootstrap"
import Image from 'next/image'
import dummy from '../public/images/dummy.png'
import Card from '../Components/Card'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Holo -Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    <main>
     <div className="customContainer height500">
       <Row>
         <Col xl={7}>
           <p className="t1t2 pdinT-100">We empower solving problems</p>
           <p className="body"> We exist to design a better world together. We try to understand the problems around us while we solve them one at a time.</p>
            <p className='overline'>Scroll to see Featured work</p>
         </Col>
         <Col xs={5}></Col>
       </Row>
     </div>
     <div className="customContainer pdinT-80M" style={{minHeight:'600px'}}>
       <Row>
         <Card/>
         <Card/>
         <Card/>
         <Card/>
         <Card/>
       </Row>
     </div>
    </main>
    </div>
  )
}
