import Head from 'next/head'
import { Container,Row,Col } from "react-bootstrap"
import Image from 'next/image'
import dummy from '../public/images/dummy.png'
import Card from '../Components/Card'
export default function Work() {
  return (
    <div>
      <Head>
        <title>Holo -Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    <main>
        <br />
        <br />
     <div className="customContainer" style={{minHeight:'600px'}}>
       <Row>
       <Card/>
         <Card/>
         <Card/>
         <Card/>
         <Card/>     
         <Card/>
         <Card/>
         <Card/>
         <Card/>
         <Card/>
       </Row>
     </div>
    </main>
    </div>
  )
}
