import Head from 'next/head'
import { Container,Row,Col } from "react-bootstrap"
import Image from 'next/image'
import dummy from '../public/images/dummy.png'
export default function Work() {
  return (
    <div>
      <Head>
        <title>Holo -Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    <main>
        <br />
        <br />
     <div className="customContainer" style={{minHeight:'600px'}}>
       <Row>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
         <Col xl={6} lg={6} md={6}>
           <div className='card1'>
            <div><Image src={dummy} height={482} width={850}/></div>
            <div>
              <h2>Daktar Bondhu - Reimagining a healthcare brand</h2>
              <p className="body">Bringing the idea of a boutique tea shop to life with visual brand identity and packaging.</p>
            </div>
           </div>
         </Col>
       </Row>
     </div>
    </main>
    </div>
  )
}
